# John Rinehart's custom espanso configuration

name: johnrichardrinehart
parent: default

matches:
  - trigger: ":raison"
    replace: "raison d'être"
  - trigger: ":g@gh"
    replace: "git@github.com:"
